spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:14b
          temperature: 0.1
          repeat-penalty: 1.15
          num-ctx: 8192
          top-p: 0.8
      embedding:
        model: bge-m3